name: Datapackage → Quarto PDF → GitHub Release
description: Generate a Quarto PDF from datapackage.json and publish it as a GitHub Release asset bundle.

inputs:
  tag:
    description: Release tag (e.g., v1.0.0)
    required: true
  release_name:
    description: Release name (defaults to tag)
    required: false
    default: ""
  release_body:
    description: Release notes/body
    required: false
    default: ""

  datapackage_path:
    description: Path to datapackage.json
    required: false
    default: datapackage.json
  qmd_output:
    description: Output .qmd path
    required: false
    default: datapackage.qmd
  pdf_output:
    description: Output .pdf path
    required: false
    default: datapackage.pdf
  data_paths:
    description: |
      Newline-separated list of data files to include in the zip.
      Example:
        datos.csv
        another.csv
        data/subdir/file.parquet
    required: false
    default: ""
  identity:
    description: Optional brand identity (e.g., mefp)
    required: false
    default: ""
  project:
    description: Optional project name to display under the header
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Generate QMD
      shell: bash
      run: |
        python "${{ github.action_path }}/datapackage2md.py" "${{ inputs.datapackage_path }}" "${{ inputs.qmd_output }}" --identity "${{ inputs.identity }}" --project "${{ inputs.project }}"

    - name: Sync style assets
      shell: bash
      run: |
        if [ ! -f "linea.tex" ]; then
          cp "${{ github.action_path }}/linea.tex" "./linea.tex"
        fi
        if [ ! -d "fonts" ]; then
          cp -R "${{ github.action_path }}/fonts" "./fonts"
        fi
        if [ ! -d "assets" ]; then
          cp -R "${{ github.action_path }}/assets" "./assets"
        fi

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

    - name: Install TeX packages
      shell: bash
      run: |
        set -e
        if ! command -v tlmgr >/dev/null 2>&1; then
          quarto install tinytex --no-prompt
        fi
        if ! command -v tlmgr >/dev/null 2>&1; then
          for d in "$HOME/.TinyTeX/bin"/*; do
            if [ -d "$d" ]; then
              export PATH="$d:$PATH"
            fi
          done
        fi
        if ! command -v tlmgr >/dev/null 2>&1; then
          echo "tlmgr not found after TinyTeX install" >&2
          exit 1
        fi
        tlmgr install fontspec titlesec booktabs colortbl xcolor

    - name: Render PDF
      shell: bash
      run: |
        set +e
        mkdir -p .texmf-var .texmf-config
        quarto render "${{ inputs.qmd_output }}" --to pdf
        rc=$?
        set -e

        produced="${{ inputs.qmd_output }}"
        produced="${produced%.qmd}.pdf"

        if [ -f "$produced" ]; then
          mv "$produced" "${{ inputs.pdf_output }}"
          echo "PDF created at ${{ inputs.pdf_output }} (quarto exit code: $rc)"
          exit 0
        fi

        exit $rc
      env:
        TEXMFVAR: ${{ github.workspace }}/.texmf-var
        TEXMFCONFIG: ${{ github.workspace }}/.texmf-config
        TEXMFHOME: ${{ github.workspace }}/.texmf-home

    - name: Bundle artifacts
      shell: bash
      run: |
        rm -rf dist
        mkdir -p dist
        cp "${{ inputs.pdf_output }}" dist/

        while IFS= read -r p; do
          [ -z "$p" ] && continue
          cp "$p" dist/
        done << 'EOF'
        ${{ inputs.data_paths }}
        EOF

        repo_name="${GITHUB_REPOSITORY##*/}"
        zip_name="${repo_name}_${{ inputs.tag }}.zip"
        echo "RELEASE_ZIP=${zip_name}" >> "$GITHUB_ENV"
        (cd dist && zip -r "../${zip_name}" .)

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ inputs.release_name != '' && inputs.release_name || inputs.tag }}
        body: ${{ inputs.release_body }}
        files: |
          ${{ env.RELEASE_ZIP }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
