name: Datapackage → Quarto PDF → GitHub Release
description: Generate a Quarto PDF from datapackage.json and publish it as a GitHub Release asset bundle.

inputs:
  tag:
    description: Release tag (e.g., v1.0.0)
    required: true
  release_name:
    description: Release name (defaults to tag)
    required: false
    default: ""
  release_body:
    description: Release notes/body
    required: false
    default: ""

  datapackage_path:
    description: Path to datapackage.json
    required: false
    default: datapackage.json
  identity:
    description: Optional brand identity (e.g., mefp)
    required: false
    default: ""
  project:
    description: Optional project name to display under the header
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Sync style assets
      shell: bash
      run: |
        if [ ! -f "linea.tex" ]; then
          cp "${{ github.action_path }}/linea.tex" "./linea.tex"
        fi
        if [ ! -d "fonts" ]; then
          cp -R "${{ github.action_path }}/fonts" "./fonts"
        fi
        if [ ! -d "assets" ]; then
          cp -R "${{ github.action_path }}/assets" "./assets"
        fi

    - name: Setup Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        tinytex: true

    - name: Install TeX packages
      shell: bash
      run: |
        set -e
        if ! command -v tlmgr >/dev/null 2>&1; then
          quarto install tinytex --no-prompt
        fi
        if ! command -v tlmgr >/dev/null 2>&1; then
          for d in "$HOME/.TinyTeX/bin"/*; do
            if [ -d "$d" ]; then
              export PATH="$d:$PATH"
            fi
          done
        fi
        if ! command -v tlmgr >/dev/null 2>&1; then
          echo "tlmgr not found after TinyTeX install" >&2
          exit 1
        fi
        tlmgr install fontspec titlesec booktabs colortbl xcolor

    - name: Build PDFs and zips
      shell: bash
      run: |
        mkdir -p .texmf-var .texmf-config
        bash "${{ github.action_path }}/build_artifacts.sh" \
          "${{ inputs.datapackage_path }}" \
          "${{ inputs.identity }}" \
          "${{ inputs.project }}"
      env:
        TEXMFVAR: ${{ github.workspace }}/.texmf-var
        TEXMFCONFIG: ${{ github.workspace }}/.texmf-config
        TEXMFHOME: ${{ github.workspace }}/.texmf-home

    - name: Collect release files
      shell: bash
      run: |
        shopt -s nullglob
        files=(build/dist/*.zip)
        if [ ${#files[@]} -eq 0 ]; then
          echo "No zip files found in build/dist." >&2
          exit 1
        fi
        {
          echo "RELEASE_ZIPS<<EOF"
          printf "%s\n" "${files[@]}"
          echo "EOF"
        } >> "$GITHUB_ENV"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ inputs.release_name != '' && inputs.release_name || inputs.tag }}
        body: ${{ inputs.release_body }}
        files: |
          ${{ env.RELEASE_ZIPS }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
